# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Va360Ai < Formula
  desc "VA360 AI Stack — One command to configure any AI coding agent on any OS."
  homepage "https://github.com/va360labs/va360-ai"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/va360labs/va360-ai/releases/download/v0.1.0/va360-ai_0.1.0_darwin_amd64.tar.gz"
      sha256 "1d7a9c6c9af652e1eede50ae3b1cb6559a15e430f381b866d35e577b2e9cd300"

      define_method(:install) do
        bin.install "va360-ai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/va360labs/va360-ai/releases/download/v0.1.0/va360-ai_0.1.0_darwin_arm64.tar.gz"
      sha256 "a1a2c23a701e888e7167103ffa64183ce6fdfe865e4bab56fdd08c7a2438449f"

      define_method(:install) do
        bin.install "va360-ai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/va360labs/va360-ai/releases/download/v0.1.0/va360-ai_0.1.0_linux_amd64.tar.gz"
      sha256 "33e3def236bb46b383d398a6905ac06df3352f7183a44ccdc935e31e2525a24b"
      define_method(:install) do
        bin.install "va360-ai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/va360labs/va360-ai/releases/download/v0.1.0/va360-ai_0.1.0_linux_arm64.tar.gz"
      sha256 "bcb3e7dab3b32f6ad9ba962a254291794c8baeb452060b3cff5088e6893f2a9e"
      define_method(:install) do
        bin.install "va360-ai"
      end
    end
  end
end
